/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klijent;

import java.awt.Color;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Security;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SecretKey;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import poruka.Poruka;

/**
 *
 * @author Raka
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    private String korisnickoIme = "";
    private String lozinka = "";
    private String putanjaDoSertifikata = "";
    private static String putanjaDoKljuceva = "";
    private static Poruka poruka;
    private static final int PORT=9000;
    private static ObjectOutputStream out;
    private static ObjectInputStream in;
    private static Socket sock;
    private static PublicKey javniKljucKlijenta;
    private static PublicKey javniKljucServera;
    private static PrivateKey privatniKljucKlijenta;
    private static SecretKey sesijskiKljuc;

    public LoginGUI() {
        initComponents();
        this.setTitle("Prijava na sistem");
        neuspjesnoLogovanjeLabel.setForeground(Color.red);
        setLocationRelativeTo(null);
        try {
            Security.addProvider(new BouncyCastleProvider());
            InetAddress addr = InetAddress.getByName("127.0.0.1");
            sock = new Socket(addr, PORT);
            out = new ObjectOutputStream(sock.getOutputStream());
            in = new ObjectInputStream(sock.getInputStream());

            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        korisnickoImeLabel = new javax.swing.JLabel();
        lozinkaLabel = new javax.swing.JLabel();
        korisnickoImeTextBox = new javax.swing.JTextField();
        lozinkaTextField = new javax.swing.JPasswordField();
        neuspjesnoLogovanjeLabel = new javax.swing.JLabel();
        prijavaButton = new javax.swing.JButton();
        sertifikatPutanjaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sertifikatPutanjaTextArea = new javax.swing.JTextArea();
        sertifikatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        korisnickoImeLabel.setText("Korisničko ime: ");

        lozinkaLabel.setText("Lozinka: ");

        neuspjesnoLogovanjeLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        prijavaButton.setText("Prijava");
        prijavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavaButtonActionPerformed(evt);
            }
        });

        sertifikatPutanjaLabel.setText("Sertifikat: ");

        sertifikatPutanjaTextArea.setEditable(false);
        sertifikatPutanjaTextArea.setColumns(1);
        sertifikatPutanjaTextArea.setLineWrap(true);
        sertifikatPutanjaTextArea.setRows(1);
        sertifikatPutanjaTextArea.setTabSize(4);
        sertifikatPutanjaTextArea.setMinimumSize(new java.awt.Dimension(0, 12));
        jScrollPane2.setViewportView(sertifikatPutanjaTextArea);

        sertifikatButton.setText("Sertifikat");
        sertifikatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sertifikatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prijavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sertifikatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(korisnickoImeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(lozinkaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sertifikatPutanjaLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(korisnickoImeTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(lozinkaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(neuspjesnoLogovanjeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korisnickoImeLabel)
                    .addComponent(korisnickoImeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lozinkaLabel)
                    .addComponent(lozinkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sertifikatPutanjaLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sertifikatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(neuspjesnoLogovanjeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(prijavaButton)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prijavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijavaButtonActionPerformed
        neuspjesnoLogovanjeLabel.setText("Pogrešno korisničko ime ili lozinka");
        char[] lozinkaChar = lozinkaTextField.getPassword();
        //lozinka = String.valueOf(lozinkaChar);
        korisnickoIme = korisnickoImeTextBox.getText();
        putanjaDoSertifikata = sertifikatPutanjaTextArea.getText();
        System.out.println("Korisnicko ime:" + korisnickoIme + ", Lozinka: " + String.valueOf(lozinkaChar) + ", Putanja do sertifikata: " + putanjaDoSertifikata);
        try {
           // PomocnaKlasa.hashLozinke(lozinkaChar);
            KeyPair parKljuceva = PomocnaKlasa.procitajKljuceve(putanjaDoKljuceva);//putanja do sertifikata
            javniKljucKlijenta = parKljuceva.getPublic();
            privatniKljucKlijenta = parKljuceva.getPrivate();
            System.out.println("javni kljuc: " + javniKljucKlijenta.toString());
            System.out.println("privatni kluc : " + privatniKljucKlijenta.toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_prijavaButtonActionPerformed

    private void sertifikatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sertifikatButtonActionPerformed
        String izabraniFolder = "";
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter(".cer", "cer");
        sertifikatPutanjaTextArea.setText("");
        JFileChooser fajl = new JFileChooser();
        fajl.setFileFilter(fileFilter);
        fajl.setCurrentDirectory(new java.io.File("."));
        fajl.setDialogTitle("Putanja do sertifikata");
        fajl.setFileSelectionMode(JFileChooser.FILES_ONLY);

        //  fajl.setAcceptAllFileFilterUsed(false);
        if (fajl.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            izabraniFolder = fajl.getSelectedFile().getAbsolutePath();
            System.out.println("getSelectedFile() : " + fajl.getSelectedFile());
        } else {
            System.out.println("No Selection ");
        }
        sertifikatPutanjaTextArea.setText(izabraniFolder);
    }//GEN-LAST:event_sertifikatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel korisnickoImeLabel;
    private javax.swing.JTextField korisnickoImeTextBox;
    private javax.swing.JLabel lozinkaLabel;
    private javax.swing.JPasswordField lozinkaTextField;
    private javax.swing.JLabel neuspjesnoLogovanjeLabel;
    private javax.swing.JButton prijavaButton;
    private javax.swing.JButton sertifikatButton;
    private javax.swing.JLabel sertifikatPutanjaLabel;
    private javax.swing.JTextArea sertifikatPutanjaTextArea;
    // End of variables declaration//GEN-END:variables
}
