/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klijent;

import pomocneKlase.PomocnaKlasaKriptografija;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Security;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SecretKey;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import pomocneKlase.PomocnaKlasaBajt;
import pomocneKlase.PomocnaKlasaSlanjePrimanje;
import poruka.Poruka;

/**
 *
 * @author Raka
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    private String korisnickoIme = "";
    private String lozinka = "";
    private String putanjaDoSertifikata = "";
    private static String putanjaDoKljuceva = "./kljucevi/";
    private static Poruka poruka;
    private static final int PORT = 9000;
    private static ObjectOutputStream out;
    private static ObjectInputStream in;
    private static Socket sock;
    private static PublicKey javniKljucKlijenta;
    private static PublicKey javniKljucServera;
    private static PrivateKey privatniKljucKlijenta;
    private static PrivateKey privatniKljucServera;
    private static SecretKey sesijskiKljuc;

    public LoginGUI() {
        initComponents();
        this.setTitle("Prijava na sistem");
        neuspjesnoLogovanjeLabel.setForeground(Color.red);
        setLocationRelativeTo(null);

        // javniKljucServera = PomocnaKlasa.procitajKljuceve("./kljucevi/server").getPublic();
        try {
//            FileInputStream fis = new FileInputStream(new File("./sertifikati/server.crt"));
//            CertificateFactory cf = CertificateFactory.getInstance("X.509");
//            X509Certificate sertifikatServera = (X509Certificate) cf.generateCertificate(fis);
//            javniKljucServera = sertifikatServera.getPublicKey();
            KeyPair parKljucevaServera = PomocnaKlasaKriptografija.procitajKljuceve("./kljucevi/server");
            javniKljucServera = parKljucevaServera.getPublic();
            privatniKljucServera = parKljucevaServera.getPrivate();
            System.out.println("JAVNI KLJUC SERVERA: " + javniKljucServera.toString() + "\n\n ");
            System.out.println("Privatni KLJUC SERVERA: " + privatniKljucServera.toString() + "\n\n ");

            Security.addProvider(new BouncyCastleProvider());
            InetAddress addr = InetAddress.getByName("127.0.0.1");
            sock = new Socket(addr, PORT);
            out = new ObjectOutputStream(sock.getOutputStream());
            in = new ObjectInputStream(sock.getInputStream());

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        korisnickoImeLabel = new javax.swing.JLabel();
        lozinkaLabel = new javax.swing.JLabel();
        korisnickoImeTextBox = new javax.swing.JTextField();
        lozinkaTextField = new javax.swing.JPasswordField();
        neuspjesnoLogovanjeLabel = new javax.swing.JLabel();
        prijavaButton = new javax.swing.JButton();
        sertifikatPutanjaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sertifikatPutanjaTextArea = new javax.swing.JTextArea();
        sertifikatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        korisnickoImeLabel.setText("Korisničko ime: ");

        lozinkaLabel.setText("Lozinka: ");

        neuspjesnoLogovanjeLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        prijavaButton.setText("Prijava");
        prijavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavaButtonActionPerformed(evt);
            }
        });

        sertifikatPutanjaLabel.setText("Sertifikat: ");

        sertifikatPutanjaTextArea.setEditable(false);
        sertifikatPutanjaTextArea.setColumns(1);
        sertifikatPutanjaTextArea.setLineWrap(true);
        sertifikatPutanjaTextArea.setRows(1);
        sertifikatPutanjaTextArea.setTabSize(4);
        sertifikatPutanjaTextArea.setMinimumSize(new java.awt.Dimension(0, 12));
        jScrollPane2.setViewportView(sertifikatPutanjaTextArea);

        sertifikatButton.setText("Sertifikat");
        sertifikatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sertifikatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(korisnickoImeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lozinkaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sertifikatPutanjaLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(neuspjesnoLogovanjeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sertifikatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(korisnickoImeTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lozinkaTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prijavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korisnickoImeLabel)
                    .addComponent(korisnickoImeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lozinkaLabel)
                    .addComponent(lozinkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sertifikatPutanjaLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sertifikatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(neuspjesnoLogovanjeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prijavaButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prijavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijavaButtonActionPerformed
        Security.addProvider(new BouncyCastleProvider());
        if (!korisnickoImeTextBox.getText().equals("") || lozinkaTextField.getPassword().length != 0) {
            neuspjesnoLogovanjeLabel.setText("");
            korisnickoIme = korisnickoImeTextBox.getText();
            char[] lozinkaChar = lozinkaTextField.getPassword();
            putanjaDoSertifikata = sertifikatPutanjaTextArea.getText();
            //lozinka = String.valueOf(lozinkaChar);

            System.out.println("Korisnicko ime:" + korisnickoIme + ", Lozinka: " + String.valueOf(lozinkaChar) + ", Putanja do sertifikata: " + putanjaDoSertifikata + "");
            try {
                // PomocnaKlasa.hashLozinke(lozinkaChar);
                System.out.println(putanjaDoKljuceva + korisnickoIme + "");
                //KeyPair parKljuceva = PomocnaKlasa.procitajKljuceve(putanjaDoKljuceva + korisnickoIme);
                KeyPair parKljuceva = PomocnaKlasaKriptografija.procitajKljuceve(putanjaDoKljuceva + korisnickoIme);
                javniKljucKlijenta = parKljuceva.getPublic();
                System.out.println("JAVNI KLJUC KLIJENTA: žn" + javniKljucKlijenta);
                privatniKljucKlijenta = parKljuceva.getPrivate();
                //sesijski kljuc 
                sesijskiKljuc = PomocnaKlasaKriptografija.generisiSesijskiKljuc();

                System.out.println("====SESIJSKI KLJUC:+++++++" + sesijskiKljuc + " VELICINA SESIJSKOG KLJUCA: " + sesijskiKljuc.getAlgorithm());

                Poruka poruka = new Poruka(Poruka.IdPoruke.SESIJSKI_KLJUC, sesijskiKljuc); //konstruktor u Poruka (id, Object, Potpis)

                System.out.println("PROVJERA OBJEKTA poruka kod klijenta " + poruka);
                System.out.println("PROVJERA OBJEKTA getOut kod klijenta " + getOut());
              //  Potpis potpis = PomocnaKlasaKriptografija.potpisivanjePoruke(poruka, privatniKljucKlijenta);
//                System.out.println("|P O T P I S!!!!!!!!" + potpis);
//                poruka.setPotpis(potpis);

                PomocnaKlasaSlanjePrimanje.posaljiPorukuKriptovanuJavnim(getOut(), poruka, javniKljucServera, privatniKljucKlijenta);

                Poruka porukaLogovanje = new Poruka(Poruka.IdPoruke.PRIJAVA, korisnickoIme, lozinkaChar);
                PomocnaKlasaSlanjePrimanje.posaljiPotpisanuPorukuKriptovanuSesijskim(out, porukaLogovanje, privatniKljucKlijenta, sesijskiKljuc);
                Poruka odgovorServera = PomocnaKlasaSlanjePrimanje.primiPotpisanuPoruku(in, javniKljucServera, sesijskiKljuc);
                // System.out.println("====Potpisana poruka: " + potpisanaPoruka.toString());
                System.out.println("ODGOVOR SERVERA NA LOGOVANJE: " + odgovorServera.getIdPoruke());
                //  byte[] kriptovanaJavnimServera = PomocnaKlasaKriptografija.enkriptujJavnimKljucem(potpisanaPoruka, javniKljucServera);
                //System.out.println("====KRIPTOVANA JAVNIM SERVERA: " + kriptovanaJavnimServera.toString());
                
                if(odgovorServera.getIdPoruke() == Poruka.IdPoruke.PRIJAVA_USPJESNA){
                    
                }
                else{
                    neuspjesnoLogovanjeLabel.setText("Pogresno korisnicko ime/lozinka!");
                }
                
                // if (logovanje Uspjesno) {
                System.out.println("====javni kljuc: " + javniKljucKlijenta.toString());
                System.out.println("====privatni kluc : " + privatniKljucKlijenta.toString());
                //    } else {
                //    neuspjesnoLogovanjeLabel.setText("Pogresni podaci za prijavu!");
                //    neuspjesnoLogovanjeLabel.setVisible(true);
                // }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            neuspjesnoLogovanjeLabel.setText("Unesite korisničke podatke!");
            neuspjesnoLogovanjeLabel.setForeground(Color.RED);
        }
    }//GEN-LAST:event_prijavaButtonActionPerformed

    private void sertifikatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sertifikatButtonActionPerformed
        String izabraniFolder = "";
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter(".cer", "cer");
        sertifikatPutanjaTextArea.setText("");
        JFileChooser fajl = new JFileChooser();
        fajl.setFileFilter(fileFilter);
        fajl.setCurrentDirectory(new java.io.File("./sertifikati"));
        fajl.setDialogTitle("Putanja do sertifikata");
        fajl.setFileSelectionMode(JFileChooser.FILES_ONLY);

        //  fajl.setAcceptAllFileFilterUsed(false);
        if (fajl.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            izabraniFolder = fajl.getSelectedFile().getAbsolutePath();
            System.out.println("getSelectedFile() : " + fajl.getSelectedFile());
        } else {
            System.out.println("No Selection ");
        }
        sertifikatPutanjaTextArea.setText(izabraniFolder);
    }//GEN-LAST:event_sertifikatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    public static ObjectOutputStream getOut() {
        return out;
    }

    public static ObjectInputStream getIn() {
        return in;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel korisnickoImeLabel;
    private javax.swing.JTextField korisnickoImeTextBox;
    private javax.swing.JLabel lozinkaLabel;
    private javax.swing.JPasswordField lozinkaTextField;
    private javax.swing.JLabel neuspjesnoLogovanjeLabel;
    private javax.swing.JButton prijavaButton;
    private javax.swing.JButton sertifikatButton;
    private javax.swing.JLabel sertifikatPutanjaLabel;
    private javax.swing.JTextArea sertifikatPutanjaTextArea;
    // End of variables declaration//GEN-END:variables
}
